- name: Automaattinen IT
  hosts: all
  become: yes
  vars:
    company_name: "Esimerkki Oy"
    domain_name: "{{ company_name | lower | replace(' ', '') }}.com"
    # Tehdään työntekijöistä lista, jotta on helpompi lisätä uusia henkilöitä
    tyontekijat:
      - first_name: "Matti"
        last_name: "Meikäläinen"
      - first_name: "Maija"
        last_name: "Meikäläinen"

  roles: 
    - common
    - web
    - users

  handlers:
    - name: Restart Caddy
      service: 
        name: caddy
        state: restarted
