- name: Luo uusi käyttäjä ja generoi SSH
  user:
    name: "{{ username }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: Käyttäjäraportti rootille
  file: 
    path: /root/user_reports
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Luo raportti 
  copy:
    content: |
      TYÖNTEKIJÄRAPORTTI
      -----------------------
      Koko nimi: {{ first_name }} {{ last_name }}
      Käyttäjätunnus: {{ username }}
      Sähköposti: {{ username }}@{{ domain_name }}
      Julkinen SSH-avain: {{ lookup('file', '/home/' + username + '/.ssh/id_rsa.pub') }}
      -----------------------
    dest: "/root/user_reports/info_{{ username }}.txt"
    owner: root
    group: root
    mode: '0600'
        
