- name: www-hakemisto
  file:
    path: /var/www/html
    state: directory
    mode: '0777'

- name: Luo web-sivun
  template: 
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Caddyfilen asetus
  copy: 
    content: |
      http://localhost, http://{{ domain_name }} {
          root * /var/www/html
          file_server
      }
    dest: /etc/caddy/Caddyfile
  notify: Restart Caddy

- name: Lisää domain hosts-tiedostoon
  lineinfile:
    path: /etc/hosts
<<<<<<< HEAD
    line: "127.0.0.1 ’{{ domain_name }}"
=======
    line: "127.0.0.1 {{ domain_name }}"
>>>>>>> 0616bd3ae4f6f9ef0446c6a578c5d9a2f8fcecd1
    state: present
    
