- name: Asenna paketit
  apt: 
    name: [curl, micro, libreoffice, caddy, ufw, acl, tree]
    state: present
    update_cache: yes
    
- name: Luo aliakset terminaali komennoille
  copy:
    dest: /etc/profile.d/termaliakset.sh
    content: |
      alias update='sudo apt update && sudo apt upgrade -y'
    owner: root
    group: root
    mode: "0644"

- name: Salli SSH-yhteydet palomuurissa
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Kytke palomuuri päälle
  community.general.ufw:
    state: enabled
    policy: deny
